### ISSUE TITLE
Profile command no longer works

### ISSUE THREAD

**Issue by tonyxiao** [nomad/cupertino#195]
```
Tony:(master)$ ios profiles --trace
/Users/Tony/.rvm/gems/ruby-2.0.0-p195/gems/cupertino-1.3.0/lib/cupertino/provisioning_portal/agent.rb:210:in `list_profiles': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/Tony/.rvm/gems/ruby-2.0.0-p195/gems/cupertino-1.3.0/lib/cupertino/provisioning_portal/commands/profiles.rb:9:in `block (3 levels) in <top (required)>'
	from /Users/Tony/.rvm/gems/ruby-2.0.0-p195/gems/cupertino-1.3.0/lib/cupertino/provisioning_portal/helpers.rb:58:in `try'
	from /Users/Tony/.rvm/gems/ruby-2.0.0-p195/gems/cupertino-1.3.0/lib/cupertino/provisioning_portal/commands/profiles.rb:9:in `block (2 levels) in <top (required)>'
	from /Users/Tony/.rvm/gems/ruby-2.0.0-p195/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
	from /Users/Tony/.rvm/gems/ruby-2.0.0-p195/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
	from /Users/Tony/.rvm/gems/ruby-2.0.0-p195/gems/commander-4.2.1/lib/commander/command.rb:155:in `run'
	from /Users/Tony/.rvm/gems/ruby-2.0.0-p195/gems/commander-4.2.1/lib/commander/runner.rb:419:in `run_active_command'
	from /Users/Tony/.rvm/gems/ruby-2.0.0-p195/gems/commander-4.2.1/lib/commander/runner.rb:81:in `run!'
	from /Users/Tony/.rvm/gems/ruby-2.0.0-p195/gems/commander-4.2.1/lib/commander/delegates.rb:8:in `run!'
	from /Users/Tony/.rvm/gems/ruby-2.0.0-p195/gems/commander-4.2.1/lib/commander/import.rb:10:in `block in <top (required)>'

```

Maybe apple just changed their provisioning portal website?

**Comment by tonyxiao** [comment]
On that note listing app_ids is also broken. I wonder if the whole thing broke rather than just profiles. Gonna check other commands.

**Comment by danieljimenez** [comment]
This is heart breaking!

**Comment by danieljimenez** [comment]
I have limited Ruby knowledge, however I stuck this in the debugger and found the following error while trying to download profiles:

```
"{
    "creationTimestamp": "2015-04-12T18:20:38Z",
    "errorMessagesForXcode": null,
    "httpCode": 200,
    "protocolVersion": "QH65B2",
    "requestId": "",
    "requestUrl": "https://developer.apple.com:443//services-account/QH65B2/account/ios/profile/listProvisioningProfiles.action?content-type=text/x-url-arguments&accept=application/json&requestId=<snip>&userLocale=en_US&teamId=<snip>&includeInactiveProfiles=true&onlyCountLists=true&type=limited",
    "responseId": "169b5555-af2e-4e7d-90b6-a9394938ed5d",
    "resultCode": 35,
    "resultString": "There were errors in the data supplied. Please correct and re-submit.",
    "suppressed": [],
    "userLocale": "en_US",
    "userString": "An invalid value &#x27;0&#x27; was provided for the parameter &#x27;pageSize&#x27;.\nAn invalid value &#x27;0&#x27; was provided for the parameter &#x27;pageNumber&#x27;.",
    "validationMessages": [
        {
            "validationKey": "pageSize",
            "validationUserMessage": "An invalid value &#x27;0&#x27; was provided for the parameter &#x27;pageSize&#x27;."
        },
        {
            "validationKey": "pageNumber",
            "validationUserMessage": "An invalid value &#x27;0&#x27; was provided for the parameter &#x27;pageNumber&#x27;."
        }
    ]
}"
```

**Comment by KrauseFx** [comment]
This is already fixed with https://github.com/nomad/cupertino/pull/196, just waiting for a merge here.
