### ISSUE TITLE
Any command app_ids/certificates/devices/profiles causes same error `error: undefined method `each' for nil:NilClass.`

### ISSUE THREAD

**Issue by grisevg** [nomad/cupertino#214]
```
Mac-Admin:~ admin$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
Mac-Admin:~ admin$ gem --version
2.0.14
```

Any command app_ids/certificates/devices/profiles causes same error `error: undefined method 'each' for nil:NilClass.`.

Here's full trace:
```
/Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.0/lib/cupertino/provisioning_portal/agent.rb:124:in `list_devices': undefined method `each' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.0/lib/cupertino/provisioning_portal/commands/devices.rb:6:in `block (3 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.0/lib/cupertino/provisioning_portal/helpers.rb:58:in `try'
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.0/lib/cupertino/provisioning_portal/commands/devices.rb:6:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/command.rb:155:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/runner.rb:419:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/runner.rb:81:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/delegates.rb:8:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.2.1/lib/commander/import.rb:10:in `block in <top (required)>'
```

**Comment by sfransen** [comment]
You have a lot of appid

You need to change the page count number

**Comment by grisevg** [comment]
Sorry, turns out I was using old version of cupertino. DERP
