### ISSUE TITLE
WWDC broke my build: UnexpectedContentError with "ios profiles" commands

### ISSUE THREAD

**Issue by ewanmellor** [nomad/cupertino#218]
This started today.  Thanks Apple.

This affects at least `profiles:devices:list`, `profiles:manage:devices`, `profiles:list`, `profiles:download`, `profiles:download:all`.

```
ios --trace profiles:download:all

/Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.1/lib/cupertino/provisioning_portal/agent.rb:188:in `list_profiles': Cupertino::ProvisioningPortal::UnexpectedContentError (Cupertino::ProvisioningPortal::UnexpectedContentError)
        from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.1/lib/cupertino/provisioning_portal/commands/profiles.rb:76:in `block (3 levels) in <top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.1/lib/cupertino/provisioning_portal/helpers.rb:58:in `try'
        from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.1/lib/cupertino/provisioning_portal/commands/profiles.rb:76:in `block (2 levels) in <top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/runner.rb:428:in `run_active_command'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/runner.rb:68:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.2/lib/commander/import.rb:8:in `block in <top (required)>'
```

**Comment by sfransen** [comment]
The portal is down check it manually and you will see

**Comment by ewanmellor** [comment]
Yes, you beat me by 16 seconds ;-)  I'll close this bug for now, see if it works when it comes back.

**Comment by benbates** [comment]
Looks like it is still broken

**Comment by ewanmellor** [comment]
I'm having no problems now, once my team agent had approved all the new Ts & Cs.
