### ISSUE TITLE
Not able to get information from Apple Enterprise account. No errors in Developer account

### ISSUE THREAD

**Issue by bitsofparag** [nomad/cupertino#223]
After installing Cupertino, I try to run the devices and profiles command and I get an option to pick between the Enterprise or Developer account. When I pick the Enterprise account, I get the following error:

```
/Users/paragm/.rvm/gems/ruby-2.0.0-p353/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:117:in `list_devices': Cupertino::ProvisioningPortal::UnexpectedContentError (Cupertino::ProvisioningPortal::UnexpectedContentError)
    from /Users/paragm/.rvm/gems/ruby-2.0.0-p353/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/devices.rb:6:in `block (3 levels) in <top (required)>'
    from /Users/paragm/.rvm/gems/ruby-2.0.0-p353/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/helpers.rb:58:in `try'
    from /Users/paragm/.rvm/gems/ruby-2.0.0-p353/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/devices.rb:6:in `block (2 levels) in <top (required)>'
    from /Users/paragm/.rvm/gems/ruby-2.0.0-p353/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    from /Users/paragm/.rvm/gems/ruby-2.0.0-p353/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    from /Users/paragm/.rvm/gems/ruby-2.0.0-p353/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
    from /Users/paragm/.rvm/gems/ruby-2.0.0-p353/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
    from /Users/paragm/.rvm/gems/ruby-2.0.0-p353/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
    from /Users/paragm/.rvm/gems/ruby-2.0.0-p353/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
    from /Users/paragm/.rvm/gems/ruby-2.0.0-p353/gems/commander-4.3.4/lib/commander/import.rb:8:in `block in <top (required)>'
```

There's no error in the Developer account. There are devices and profiles stored in the Enterprise account

**Comment by m4rkk** [comment]
I'm seeing this too with one of my appleId, however the other seems to work - both are admins
