### ISSUE TITLE
Cupertino::ProvisioningPortal::UnexpectedContentError for ios profiles:list

### ISSUE THREAD

**Issue by 23tux** [nomad/cupertino#227]
Hi,

when I try to run `ios profiles:list -u my@email.com` I get the following error:

```
/Users/myUser/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:188:in `list_profiles': Cupertino::ProvisioningPortal::UnexpectedContentError (Cupertino::ProvisioningPortal::UnexpectedContentError)
	from /Users/myUser/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/profiles.rb:9:in `block (3 levels) in <top (required)>'
	from /Users/myUser/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/helpers.rb:58:in `try'
	from /Users/myUser/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/profiles.rb:9:in `block (2 levels) in <top (required)>'
	from /Users/myUser/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/myUser/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/myUser/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/myUser/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/myUser/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/myUser/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/myUser/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/import.rb:5:in `block in <top (required)>'
```

Any idea how to fix this?

**Comment by 23tux** [comment]
I just found out, that I hadn't agreed to some license stuff that showed up after login (https://developer.apple.com/membercenter). The error message was kinda confusing.
