### ISSUE TITLE
New Developer Portal, New Woes

### ISSUE THREAD

**Issue by danieljimenez** [nomad/cupertino#228]
Looks like Cupertino is getting an unexpected response from the developer portal since the changes last night. :(

```
$ ios profiles:download:all --username '<redacted>' --password '<redacted>' --type distribution --trace
/Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:188:in `list_profiles': Cupertino::ProvisioningPortal::UnexpectedContentError (Cupertino::ProvisioningPortal::UnexpectedContentError)
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/profiles.rb:76:in `block (3 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/helpers.rb:58:in `try'
	from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/profiles.rb:76:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/import.rb:5:in `block in <top (required)>'

```

**Comment by danieljimenez** [comment]
Never mind, I just had to agree to the new license in the portal for this account :). Sorry!
