### ISSUE TITLE
Adding a device fails with a 415 error

### ISSUE THREAD

**Issue by foozmeat** [nomad/cupertino#229]
With cupertino 1.3.4

```
/Library/Ruby/Gems/2.0.0/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:304:in `fetch': 415 => Net::HTTPUnsupportedMediaType for https://developer.apple.com/services-account/QH65B2/account/ios/device/validateDevices.action?struts.token.name=clientToken&clientToken=NI48Q6R918K8SKO5C5IHMVJHSVPT68NG&register=multiple&deviceNames=&deviceNumbers= -- unhandled response (Mechanize::ResponseCodeError)
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.5.1/lib/mechanize.rb:407:in `get'
    from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:45:in `block in get'
    from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:44:in `times'
    from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:44:in `get'
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.5.1/lib/mechanize.rb:517:in `submit'
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.5.1/lib/mechanize/form.rb:178:in `submit'
    from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:156:in `add_devices'
    from /Library/Ruby/Gems/2.0.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/devices.rb:60:in `block (2 levels) in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by objectmethod** [comment]
me too

**Comment by sfransen** [comment]
Use spaceship to do that part

**Comment by objectmethod** [comment]
Yeah, that's what I did!  Thanks

**Comment by aspcartman** [comment]
Emm, any way to fix this? I don't want to use spaceship...

**Comment by sfransen** [comment]
You just have to use a few lines os code to do add the devices have it in my Cupertino code
