### ISSUE TITLE
ProvisioningPortal::UnexpectedContentError when downloading profiles

### ISSUE THREAD

**Issue by pierre-jenchen** [nomad/cupertino#237]
Hi,
since a few days we encouter an issue with the download of the profiles. Our credentials are correct and working in the browser and ios login works, too.

We are using: cupertino (1.3.4).
There are no unanswered licence agreements open like in https://github.com/nomad/cupertino/issues/227.

But when we attempt to download profiles we get this exception:
```ruby
 ios profiles:download:all --trace
/Users/QA/.rvm/gems/ruby-2.1.2/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:188:in `list_profiles': Cupertino::ProvisioningPortal::UnexpectedContentError (Cupertino::ProvisioningPortal::UnexpectedContentError)
	from /Users/QA/.rvm/gems/ruby-2.1.2/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/profiles.rb:76:in `block (3 levels) in <top (required)>'
	from /Users/QA/.rvm/gems/ruby-2.1.2/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/helpers.rb:58:in `try'
	from /Users/QA/.rvm/gems/ruby-2.1.2/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/profiles.rb:76:in `block (2 levels) in <top (required)>'
	from /Users/QA/.rvm/gems/ruby-2.1.2/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/QA/.rvm/gems/ruby-2.1.2/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/QA/.rvm/gems/ruby-2.1.2/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/QA/.rvm/gems/ruby-2.1.2/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/QA/.rvm/gems/ruby-2.1.2/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
	from /Users/QA/.rvm/gems/ruby-2.1.2/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/QA/.rvm/gems/ruby-2.1.2/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by sfransen** [comment]
Apple broken everything
I have download working but not adding devices to existing profiles
Using Sigh

**Comment by pierre-jenchen** [comment]
Ok, i will give it a try. Thanks for help.
