### ISSUE TITLE
ios profiles:list UnexpectedContentError

### ISSUE THREAD

**Issue by levigroker** [nomad/cupertino#45]
The "profiles:list" command is returning a "UnexpectedContentError" error when executed:

```
Sequoia:jenkins labrown$ ios --version
ios 0.8.1


Sequoia:jenkins labrown$ ios profiles:list
error: Cupertino::ProvisioningPortal::UnexpectedContentError. Use --trace to view backtrace
Sequoia:jenkins labrown$ ios profiles:list --trace
/Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/cupertino-0.8.1/lib/cupertino/provisioning_portal/agent.rb:159:in `list_profiles': Cupertino::ProvisioningPortal::UnexpectedContentError (Cupertino::ProvisioningPortal::UnexpectedContentError)
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/cupertino-0.8.1/lib/cupertino/provisioning_portal/commands/profiles.rb:8:in `block (3 levels) in <top (required)>'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/cupertino-0.8.1/lib/cupertino/provisioning_portal/helpers.rb:50:in `try'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/cupertino-0.8.1/lib/cupertino/provisioning_portal/commands/profiles.rb:8:in `block (2 levels) in <top (required)>'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/command.rb:180:in `call'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/command.rb:180:in `call'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/command.rb:155:in `run'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/runner.rb:402:in `run_active_command'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/runner.rb:78:in `run!'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/delegates.rb:11:in `run!'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/import.rb:10:in `block in <top (required)>'


Sequoia:jenkins labrown$ ios profiles:list distribution
error: Cupertino::ProvisioningPortal::UnexpectedContentError. Use --trace to view backtrace
Sequoia:jenkins labrown$ ios profiles:list distribution --trace
/Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/cupertino-0.8.1/lib/cupertino/provisioning_portal/agent.rb:159:in `list_profiles': Cupertino::ProvisioningPortal::UnexpectedContentError (Cupertino::ProvisioningPortal::UnexpectedContentError)
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/cupertino-0.8.1/lib/cupertino/provisioning_portal/commands/profiles.rb:8:in `block (3 levels) in <top (required)>'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/cupertino-0.8.1/lib/cupertino/provisioning_portal/helpers.rb:50:in `try'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/cupertino-0.8.1/lib/cupertino/provisioning_portal/commands/profiles.rb:8:in `block (2 levels) in <top (required)>'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/command.rb:180:in `call'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/command.rb:180:in `call'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/command.rb:155:in `run'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/runner.rb:402:in `run_active_command'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/runner.rb:78:in `run!'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/delegates.rb:11:in `run!'
    from /Users/labrown/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/import.rb:10:in `block in <top (required)>'
```

**Comment by AshishMeshram** [comment]
I am experiencing this issue after upgrading to el capitan. 

Followed the steps here : 
http://www.hacksparrow.com/os-x-el-capitan-screwed-up-ruby-gems-and-how-to-fix-it.html

reinstalled cupertino

Authenticated myself again using $ios login still facing the issue:



$ ios profiles:list --trace
/usr/local/lib/ruby/gems/2.3.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/agent.rb:188:in `list_profiles': Cupertino::ProvisioningPortal::UnexpectedContentError (Cupertino::ProvisioningPortal::UnexpectedContentError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/profiles.rb:9:in `block (3 levels) in <top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/helpers.rb:58:in `try'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cupertino-1.3.4/lib/cupertino/provisioning_portal/commands/profiles.rb:9:in `block (2 levels) in <top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
